package io.github.tlaplus.hardening.workflow;

import io.github.tlaplus.hardening.corpus.CorpusEntryValidator;
import io.github.tlaplus.hardening.corpus.CorpusException;
import io.github.tlaplus.hardening.corpus.CorpusInventory;
import io.github.tlaplus.hardening.corpus.CorpusStage;
import io.github.tlaplus.hardening.mutation.ByteMutator;
import io.github.tlaplus.hardening.workflow.execution.WorkflowControl;
import io.github.tlaplus.hardening.workflow.input.GenerationPlan;
import io.github.tlaplus.hardening.workflow.input.InputStage;
import io.github.tlaplus.hardening.workflow.input.MutantCandidates;
import io.github.tlaplus.hardening.workflow.input.ParentPool;
import io.github.tlaplus.hardening.workflow.input.PbtCandidates;
import io.github.tlaplus.hardening.workflow.quality.QualityGate;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Objects;

/**
 * Runs the generations of one workflow invocation (ADR 0010).
 *
 * <p>Each generation is one {@link StageGraph}: its input stage admits the generation's missing
 * entries, mutated from {@code 04quality-pass} and generated by PBT in the configured ratio, and
 * the graph runs until every stage has drained. The quality gate then selects from the settled
 * generation, and the next generation starts, until the corpus holds {@code workflow.max_entries}
 * entries. A run resumes at the highest generation the corpus records, admitting the mutants and
 * PBT entries that generation still lacks; admitting nothing, draining nothing and gating nothing is
 * a no-op, so resuming a completed generation simply moves on.
 */
final class GenerationLoop {
    /** One generation and the graph that runs it. */
    record Generation(int number, StageGraph graph) {
        Generation {
            Objects.requireNonNull(graph, "graph");
        }
    }

    private final StageGraph.Setup setup;
    private final StageGraph.Invocation invocation;
    private final StageGraph.Startup startup;
    private final OccupancyLimits limits;
    private volatile Generation current;

    GenerationLoop(
            StageGraph.Setup setup,
            StageGraph.Invocation invocation,
            StageGraph.Startup startup,
            OccupancyLimits limits)
            throws IOException, CorpusException {
        this.setup = Objects.requireNonNull(setup, "setup");
        this.invocation = Objects.requireNonNull(invocation, "invocation");
        this.startup = Objects.requireNonNull(startup, "startup");
        this.limits = Objects.requireNonNull(limits, "limits");
        current = generation(startup.initial(), startup.initial().latestGeneration());
    }

    /** Returns the generation that runs now, or ran last. */
    Generation current() {
        return current;
    }

    /**
     * Runs generations until the corpus is full or a stage stops the run, and reports which. A stage
     * failure is thrown.
     */
    WorkflowRunSummary.StopReason run() throws IOException, CorpusException, WorkflowException {
        while (true) {
            var generation = current;
            var graph = generation.graph();
            graph.run();
            graph.throwIfFailed();
            if (graph.control().state() == WorkflowControl.State.CAPACITY_REACHED) {
                return WorkflowRunSummary.StopReason.CAPACITY_REACHED;
            }
            new QualityGate(
                            invocation.corpus(),
                            setup.config().mutator(),
                            graph.counters(CorpusStage.QUALITY))
                    .run(generation.number());
            // Startup validated every payload, and this build wrote every entry since.
            var inventory = invocation.corpus().recoverAndValidate(CorpusEntryValidator.NONE);
            if (inventory.totalEntries() >= setup.config().workflow().maximumEntries()) {
                return WorkflowRunSummary.StopReason.COMPLETED;
            }
            current = generation(inventory, generation.number() + 1);
        }
    }

    /**
     * Returns how many of a generation's {@code missing} entries are mutants, so that the whole
     * generation of {@code size} entries holds {@code round(feedbackRatio × size)} of them, however
     * many an interrupted run already admitted.
     */
    static long missingMutants(long size, long admittedMutants, long missing, double feedbackRatio) {
        var mutants = Math.round(feedbackRatio * size) - admittedMutants;
        return Math.max(0, Math.min(missing, mutants));
    }

    /** Builds the graph that admits the missing entries of generation {@code number}. */
    private Generation generation(CorpusInventory inventory, int number)
            throws IOException, CorpusException {
        var config = setup.config();
        var kind = config.generatedKind();
        var admitted = inventory.entries(number);
        var missing = Math.max(0, Math.min(
                config.mutator().generationSize() - admitted,
                config.workflow().maximumEntries() - inventory.totalEntries()));
        var quotas = new ArrayList<GenerationPlan.Quota>();
        if (missing > 0 && config.mutator().feedbackRatio() > 0) {
            var parents = ParentPool.load(invocation.corpus(), kind, setup.decoders().decoder(kind));
            if (!parents.isEmpty()) {
                var mutants = missingMutants(
                        admitted + missing, inventory.mutants(number), missing, config.mutator().feedbackRatio());
                quotas.add(new GenerationPlan.Quota(
                        new MutantCandidates(parents, new ByteMutator(
                                config.mutator().weights(),
                                config.mutator().maximumEdits(),
                                config.pbt().maximumInputBytes())),
                        mutants));
                missing -= mutants;
            }
        }
        quotas.add(new GenerationPlan.Quota(new PbtCandidates(config.pbt()), missing));
        var plan = new GenerationPlan(
                kind,
                number,
                InputStage.generationSeed(invocation.seed(), number),
                inventory.totalEntries(),
                invocation.maximumCpus(),
                quotas);
        var graph = new StageGraph(
                setup,
                invocation,
                new StageGraph.Startup(inventory, startup.metrics(), startup.scratch()),
                plan);
        if (limits.exhausted(inventory)) {
            graph.control().capacityReached();
        }
        return new Generation(number, graph);
    }
}
